### PR TITLE
Pydata PDX Site Updates: Markdown conversion, creating collections, design template update

### PR DESCRIPTION
**Pull request by makotonium**
@allisons has requested that the current PyData Jekyll site to be updated to allow more flexibility and maintainability. This PR is still work in progress. 

To-do at a high-level
- [x] Convert all the pages into `.md` format
- [x] Convert list items such as meetup into collections. 
- [x] Update organizers list
- [x] Update template

### CODE REVIEW

**Comment by makotonium** [comment]
@allisons , could you remind me which template you want me to swap the current one with? 

BTW this is still work-in-progress, but just wanted to start pushing changes for transparency.

**Comment by makotonium** [comment]
@allisons I think I am done converting various pages into markdowns and collections but still need to fix the layout. I now need two things from you when you get a chance.
 - Which design template you want me to use. (Sorry I can't remember)
 - The most current names for the list of organizers (for Contact page)
 Thank you! 🙏

**Comment by allisons** [comment]
> 

"Minimal mistakes"

**Comment by allisons** [comment]
> @allisons I think I am done converting various pages into markdowns and collections but still need to fix the layout. I now need two things from you when you get a chance.
> 
> * Which design template you want me to use. (Sorry I can't remember)
> * The most current names for the list of organizers (for Contact page)
>   Thank you! 🙏

I'll have to go get the best contacts for everyone and I'll get back to you

**Comment by allisons** [comment]
> @allisons I think I am done converting various pages into markdowns and collections but still need to fix the layout. I now need two things from you when you get a chance.
> 
> * Which design template you want me to use. (Sorry I can't remember)
> * The most current names for the list of organizers (for Contact page)
>   Thank you! 🙏

Allison Sliter
- she/her
- Organizer
- allison.sliter@gmail.com 
- https://www.linkedin.com/in/allisonsliter 
- asliter.com 
- https://calendly.com/allison-sliter

Vishal Bakshi
- he/him
- co-organizer
- vdbaskshi@gmail.com
- https://github.com/vishalbakshi

Tom Baldwin
- he/him
- co-organizer
- tkb@sent.com
- baldwint.com

Adam Breindel
- he/him
- co-organizer
- adbreind@gmail.com
- http://linkedin.com/in/adbreind

**Comment by makotonium** [comment]
@allisons This is ready for first review. Everything should be the way it was, except the PyDdata PDX logo overlay is currently not visible yet. I can fix it but wanted to wait if you are wanting some other graphics related changes.

**Review by allisons — COMMENTED** [review]
Looks good to me.  I'll start adding additional meetup .mds asap

**Pull request merged**
